### PR TITLE
Bumped the version to 0.32.0

### PR DESCRIPTION
**Pull request by ivoflipse**
Now doing the same thing through a fork PR instead of a branch on this repo

### CODE REVIEW

**Comment by ocefpaf** [comment]
@ivoflipse I re-started all `azure-*` packages to get the OS X and Windows binaries in the channel now that `conda-config` fixed the "drop channel" bug. (Let me know if you find anyone that is still missing.)

**Comment by Korijn** [comment]
Looks like there's still a bunch missing for Linux:

```
conda-forge/azure         |    1.0.3 | conda           | win-32, win-64, osx-64
                                     : Microsoft Azure Client Libraries for Python
conda-forge/azure-common  |    1.1.4 | conda           | linux-64, win-32, win-64, osx-64
                                     : Microsoft Azure Client Libraries for Python
conda-forge/azure-mgmt    |   0.20.1 | conda           | win-32, win-64, osx-64
                                     : Microsoft Azure Client Libraries for Python
conda-forge/azure-mgmt-common |   0.20.0 | conda           | win-32, win-64, osx-64
                                     : Microsoft Azure Resource Management Client Library for Python (Common)
conda-forge/azure-mgmt-compute |   0.20.1 | conda           | win-32, win-64, osx-64
                                     : Microsoft Azure Client Libraries for Python
conda-forge/azure-mgmt-network |   0.20.1 | conda           | win-32, win-64, osx-64
                                     : Microsoft Azure Network Resource Management Client Library for Python
conda-forge/azure-mgmt-nspkg |    1.0.0 | conda           | win-32, win-64, osx-64
                                     : Microsoft Azure Resource Management Namespace Package
conda-forge/azure-mgmt-resource |   0.20.1 | conda           | win-32, win-64, osx-64
                                     : Microsoft Azure Resource Management Client Library for Python
conda-forge/azure-mgmt-storage |   0.20.0 | conda           | win-32, win-64, osx-64
                                     : Microsoft Azure Storage Resource Management Client Library for Python
conda-forge/azure-nspkg   |    1.0.0 | conda           | linux-64, win-32, win-64, osx-64
                                     : Microsoft Azure Namespace Package [Internal]
conda-forge/azure-servicebus |   0.20.1 | conda           | win-32, win-64, osx-64
                                     : Microsoft Azure Service Bus Client Library for Python
conda-forge/azure-servicemanagement-legacy |   0.20.1 | conda           | win-32, win-64, osx-64
                                     : Microsoft Azure Legacy Service Management Client Library for Python
conda-forge/azure-storage |   0.32.0 | conda           | linux-64, win-32, win-64, osx-64
                                     : Microsoft Azure Storage Client Library for Python
```

I'm not sure how to kick off CI for that though!

**Comment by Korijn** [comment]
At least `azure-storage=0.20.3` is out there, which means we can merge this PR:

```
> anaconda show conda-forge/azure-storage/0.20.3
Using Anaconda Cloud api site https://api.anaconda.org
version 0.20.3
   + linux-64/azure-storage-0.20.3-py27_0.tar.bz2
   + linux-64/azure-storage-0.20.3-py34_0.tar.bz2
   + linux-64/azure-storage-0.20.3-py35_0.tar.bz2
   + osx-64/azure-storage-0.20.3-py27_0.tar.bz2
   + osx-64/azure-storage-0.20.3-py34_0.tar.bz2
   + osx-64/azure-storage-0.20.3-py35_0.tar.bz2
   + win-32/azure-storage-0.20.3-py27_0.tar.bz2
   + win-32/azure-storage-0.20.3-py34_0.tar.bz2
   + win-32/azure-storage-0.20.3-py35_0.tar.bz2
   + win-64/azure-storage-0.20.3-py27_0.tar.bz2
   + win-64/azure-storage-0.20.3-py34_0.tar.bz2
   + win-64/azure-storage-0.20.3-py35_0.tar.bz2
```

**Comment by Korijn** [comment]
LGTM!

**Comment by ocefpaf** [comment]
> Looks like there's still a bunch missing for Linux

@Korijn in theory Linux was not affected by the bug, but it seems that the binaries did not make into the channel even though the CIs completed successfully. You'll need to re-start them manually!! I will try one and see if the binary gets properly uploaded or if we have a deeper hidden problem.

**Comment by ivoflipse** [comment]
@ocefpaf and @Korijn I believe this also was due to the hierarchy of the packages. 

`azure-nspkg` had to be available for all the other builds to succeed. Then `azure-common` had to be there for some others. Now I presume `azure-mgmt` has to be built, before the rest will succeed as well. I hadn't gotten around to @jakirkham's instructions for restarting feedstock builds

**Comment by ocefpaf** [comment]
> @ocefpaf and @Korijn I believe this also was due to the hierarchy of the packages.

Yep. Just find that out too :smile: 

> I hadn't gotten around to @jakirkham's instructions for restarting feedstock builds

All you need to do is to click the CI icon and navigate the interface looking for the re-start button. I am doing that for you now, but you can try a few to get the hang of it.

**Comment by Korijn** [comment]
Well, I was looking for the button, but it looks like you beat me to it. :) Thanks!

**Pull request merged**
